name: pyomo-binder
channels:
  - conda-forge

dependencies:
  - python=3.12
  - scip
  - ipywidgets
  - voila
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - scikit-optimize
  - numpy
  - scipy
  - pip
  - pip:
      - dill
      - amplpy
