name: pyomo-binder
channels:
  - conda-forge
  - gurobi
dependencies:
  - python=3.12
  - gurobi
  - ipywidgets
  - voila
  - ipykernel
  - matplotlib
  - pandas
  - seaborn
  - scikit-learn
  - scikit-optimize
  - numpy
  - scipy
  - pip
  - pip:
      - dill
      - amplpy
