#!/bin/bash
cd /home/jovyan/
export PYTHONPATH=/home/jovyan/:$PYTHONPATH
# jupyter notebook --generate-config
# echo "c.NotebookApp.notebook_dir = '/home/jovyan/'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py

echo "import os">>/home/jovyan/.ipython/profile_default/startup/00-first.py
echo "" >/home/jovyan/.ipython/profile_default/startup/00-first.py
echo "os.chdir('/home/jovyan/')" >/home/jovyan/.ipython/profile_default/startup/00-first.py

exec "$@"