#!/bin/bash
cd /home/jovyan/
export PYTHONPATH=/home/jovyan/:$PYTHONPATH
jupyter notebook --generate-config
echo "c.NotebookApp.notebook_dir = '/home/jovyan/'" >> /home/jovyan/.jupyter/jupyter_notebook_config.py
exec "$@"